[package]
name = "lolupdater-gui"
version = "1.0.5"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]

[dependencies.lolupdater-core]
path = "../lolupdater-core"

[dependencies]
ui = { git = "https://github.com/davidkna/libui-rs" }
tinyfiledialogs = "3.0.4"
