language: rust
rust:
- stable
cache: cargo
script:
- brew update
- brew install cmake || true
- brew install ninja || true
- cargo build --verbose --all
- cargo test --verbose --all
os:
- osx
addons:
  apt:
    packages:
    - libgtk-3-dev
before_deploy:
  - brew install node || true
  - brew install zopfli || true
  - npm install --global create-dmg
  - ./scripts/release_build.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dzUBk53mtIp4tB1AK5jMM4pFY2hUZcU5drNhwQL3hIPJkRRLSWhxzUUbbS4fsIhU+5HjDeeSOblit9fIRKEWtuCM0L/PVZaeA/PkpCToDrkJhU3NpOe59COuI/oP+CLc4T8pDFiHMHY3ZPRUaIIAp/eL4ETTwtwGZ0uGkg9yzEI=
  file:
    - ./dist/LoLUpdater.dmg
    - ./dist/lolupdater-cli.tar.gz
  on:
    repo: LoLUpdater/LoLUpdater-macOS
    rust: stable
    os: osx
    tags: true
