[package]
name = "lolupdater-cli"
version = "3.2.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]

[dependencies.lolupdater-core]
path = "../lolupdater-core"

[dependencies]
error-chain = "~0.10.0"
app_dirs = "~1.1.1"